### PR TITLE
Add CircleCI configuration

### LINKED ISSUE #3: Add CI
https://circleci.com/docs/2.0/language-elixir/

```bash
$ mix format --check-formatted
$ mix credo --strict
$ mix test
```

### PR DESCRIPTION
**Pull request by platipo**
Fixes #3

### CODE REVIEW

**Comment by platipo** [comment]
To test the workflow I need you to activate CircleCI, the steps are the following:
  -  Go to the CircleCi page
  -  Sign up with your Github account
  -  Click "Add projects" menu and then click "Set up Project" on the  feed-me  project
  -  Go to Organization Security settings and opt-in to third party orbs feature
  -  Finally activate the forked PRs trigger build option

**Comment by platipo** [comment]
@sean-beard I set the Elixir image version to 1.10.4, do you need to test for other versions?

**Comment by sean-beard** [comment]
@platipo Thank you so much for taking the time to contribute! 

I've activated CircleCI for this repository so you should be all set to test the workflow. I think testing against only Elixir 1.10.4 is fine for now, thanks for asking 🙂 

Let me know if you need anything else!

**Comment by platipo** [comment]
I parametrized the build so in the future you can add cover many Elixir versions.

If you have a Docker user it would be better because `No authentication provided, this pull may be subject to Docker Hub download rate limits.`, you can read more about this issue [here](https://circleci.com/docs/2.0/private-images/).

The build is failing 
```
$ mix local.hex --force

** (FunctionClauseError) no function clause matching in String.split/3    
    
    The following arguments were given to String.split/3:
    
        # 1
        :enoent
    
        # 2
        "\n"
    
        # 3
        []
    
    Attempted function clauses (showing 3 out of 3):
    
        def split(string, %Regex{} = pattern, options) when is_binary(string)
        def split(string, "", options) when is_binary(string)
        def split(string, pattern, options) when is_binary(string)
    
    (elixir 1.10.4) lib/string.ex:471: String.split/3
    config/config.exs:46: DotEnv.get_env_vars/0
    config/config.exs:37: DotEnv.get_env/1
    (stdlib 3.12.1) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib 3.12.1) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib 3.12.1) erl_eval.erl:240: :erl_eval.expr/5
    (stdlib 3.12.1) erl_eval.erl:232: :erl_eval.expr/5
    (stdlib 3.12.1) erl_eval.erl:888: :erl_eval.expr_list/6
```

**Comment by sean-beard** [comment]
If you pull the latest you shouldn't get that error anymore. Should be fixed with the changes in #7 

I'll look into setting up the Docker authenticated pulls - thanks for pointing me in the right direction!

**Comment by platipo** [comment]
I see the package compiling but somewhat there is another error:
```
** (Mix) mix format failed due to --check-formatted.
The following files were not formatted:

  * priv/repo/migrations/20201016010059_create_subscriptions.exs
  * priv/repo/migrations/20201016010656_create_feed_item_statuses.exs
  * priv/repo/migrations/20201013175712_create_feeds.exs
  * priv/repo/migrations/20201013180331_create_feed_items.exs
  * priv/repo/migrations/20201016003738_create_users.exs
```

**Comment by sean-beard** [comment]
If you pull the latest those formatting errors should be gone via #8

**Comment by platipo** [comment]
Argh! New issues:
```
$ mix credo --strict

Checking 35 source files ...

info: some checks were skipped because they're not compatible with
your version of Elixir (1.10.4).

You can deactivate these checks by adding this to the `checks` list in your config:

    {Credo.Check.Refactor.MapInto, false},
    {Credo.Check.Warning.LazyLogging, false},


  Software Design                                                               
┃ 
┃ [D] ↘ Nested modules could be aliased at the top of the invoking module.
┃       test/support/data_case.ex:34:7 #(FeedMe.DataCase)
┃ [D] ↘ Nested modules could be aliased at the top of the invoking module.
┃       test/support/data_case.ex:31:11 #(FeedMe.DataCase)
┃ [D] ↘ Nested modules could be aliased at the top of the invoking module.
┃       test/support/conn_case.ex:38:7 #(FeedMeWeb.ConnCase)
┃ [D] ↘ Nested modules could be aliased at the top of the invoking module.
┃       test/support/conn_case.ex:35:11 #(FeedMeWeb.ConnCase)
┃ [D] ↘ Nested modules could be aliased at the top of the invoking module.
┃       test/support/channel_case.ex:35:7 #(FeedMeWeb.ChannelCase)
┃ [D] ↘ Nested modules could be aliased at the top of the invoking module.
┃       test/support/channel_case.ex:32:11 #(FeedMeWeb.ChannelCase)

  Code Readability                                                              
┃ 
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/feed_me_web/telemetry.ex:1:11 #(FeedMeWeb.Telemetry)
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/feed_me_web/controllers/plugs/set_user.ex:1:11 #(FeedMeWeb.Plugs.SetUser)
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/feed_me/content/feed_item.ex:1:11 #(FeedMe.Content.FeedItem)
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/feed_me/content/feed.ex:1:11 #(FeedMe.Content.Feed)
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/feed_me/account_content/subscription.ex:1:11 #(FeedMe.AccountContent.Subscription)
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/feed_me/account_content/feed_item_status.ex:1:11 #(FeedMe.AccountContent.FeedItemStatus)
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/feed_me/account/user.ex:1:11 #(FeedMe.Account.User)
┃ [R] ↘ The alias `FeedMe.Account.User` is not alphabetically ordered among its 
┃       group.
┃       lib/feed_me_web/controllers/plugs/set_user.ex:5:9 #(FeedMeWeb.Plugs.SetUser)

  Refactoring opportunities                                                     
┃ 
┃ [F] → Cond statements should contain at least two conditions besides `true`, 
┃       consider using `if` instead.
┃       lib/feed_me_web/controllers/plugs/set_user.ex:13:5 #(FeedMeWeb.Plugs.SetUser.call)
```
[CircleCI raw output](https://app.circleci.com/pipelines/github/sean-beard/feed-me/10/workflows/e4a6a564-ef69-420b-9923-91faabf08001/jobs/10/parallel-runs/0/steps/0-115)

**Comment by sean-beard** [comment]
Ahh yeah these things will need to be addressed but feel free to remove the `mix credo --strict` check for now and I can work on getting all these resolved/adding it back in later. Thanks again for all your work on this, looks great!

**Comment by platipo** [comment]
I commented out the `mix credo --strict` and let the tests run but:
```elixir
==> feed_me
Compiling 27 files (.ex)
Generated feed_me app

12:49:35.067 [error] GenServer #PID<0.5395.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for FeedMe.Repo couldn't be created: killed
```

It seems that all the pieces are working, do you want to merge? Should I revert the last commit? Let me know

**Comment by platipo** [comment]
Also, I'm working on the [orbtoberfest](https://hacktoberfest.circleci.com/) but to make this PR count I need the `Orbtoberfest` tag. Can you please add it? 🙏

**Pull request merged**
